# Generated by Django 5.2.15 on 2026-07-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conteudo', '0011_anexo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloBotao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_fundo', models.CharField(blank=True, help_text='Ex.: #2d5a8e. Vazio = automático.', max_length=20, verbose_name='Cor de fundo')),
                ('cor_texto', models.CharField(blank=True, max_length=20, verbose_name='Cor do texto')),
                ('fonte', models.CharField(blank=True, help_text='Ex.: Inter, Georgia, Arial. Vazio = fonte do site.', max_length=100, verbose_name='Fonte')),
                ('tamanho_fonte', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho da letra (px)')),
                ('alinhamento', models.CharField(blank=True, choices=[('', 'Automático'), ('left', 'Esquerda'), ('center', 'Centralizado'), ('right', 'Direita')], max_length=10, verbose_name='Alinhamento do texto')),
                ('pulsante', models.BooleanField(default=False, help_text='O botão desta categoria pulsa suavemente no site.', verbose_name='Botão vibrante/pulsante')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estilo', to='conteudo.categoria', verbose_name='Categoria (botão)')),
            ],
            options={
                'verbose_name': 'Estilo de botão',
                'verbose_name_plural': 'Estilos de botões',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('pulsante', models.BooleanField(default=False, help_text='O card deste conteúdo pulsa suavemente neste local do site.', verbose_name='Botão vibrante/pulsante')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='conteudo.categoria', verbose_name='Categoria (local de exibição)')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='conteudo.conteudo', verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Vínculo de publicação',
                'verbose_name_plural': 'Vínculos de publicação',
                'ordering': ['categoria', 'ordem'],
                'unique_together': {('conteudo', 'categoria')},
            },
        ),
    ]
