# Generated by Django 5.2.15 on 2026-07-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilobotao',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('', 'Automático (tamanho padrão)'), ('pequeno', 'Pequeno'), ('medio', 'Médio (padrão)'), ('grande', 'Grande')], help_text='Controla o tamanho do botão (e dos subbotões dentro dele) no site.', max_length=10, verbose_name='Tamanho do botão'),
        ),
    ]
