# Generated by Django 5.2.15 on 2026-07-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_estilobotao_tamanho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculo',
            options={'ordering': ['categoria', 'ordem'], 'permissions': [('pode_acessar_painel_central', 'Pode acessar: Painel Administrativo Completo')], 'verbose_name': 'Vínculo de publicação', 'verbose_name_plural': 'Vínculos de publicação'},
        ),
    ]
