# Generated by Django 5.2.15 on 2026-07-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0004_banner_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='icone_manual',
            field=models.CharField(blank=True, help_text='Deixe em branco para o site escolher um ícone automaticamente com base no título e na categoria.', max_length=50, verbose_name='Ícone do card'),
        ),
    ]
