# Generated by Django 5.2.15 on 2026-07-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0008_config_home_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='recente',
            field=models.BooleanField(default=False, help_text='Se marcado, este item aparece na seção "Conteúdos recentes" da home (abaixo do banner, à esquerda). Se desmarcado, aparece só na categoria escolhida.', verbose_name='Aparecer em "Conteúdos recentes"'),
        ),
    ]
