# Generated by Django 5.2.15 on 2026-07-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0009_conteudo_recente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Formatos aceitos: PDF, Word (.doc/.docx), Excel (.xls/.xlsx), PowerPoint (.ppt/.pptx), vídeo (.mp4/.avi), imagem (.jpg/.png) e outros.', null=True, upload_to='documentos/%Y/%m/', verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='PDF, Word, Excel, PowerPoint, vídeo, imagem ou outro arquivo.', upload_to='anexos/%Y/%m/', verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, help_text='Nome exibido no site. Se vazio, usa o nome do arquivo.', max_length=200, verbose_name='Nome do arquivo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='conteudo.conteudo', verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
