# Generated by Django 5.2.15 on 2026-07-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0010_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='conteudo.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='conteudo.conteudo', verbose_name='Conteúdo'),
        ),
    ]
