# Generated by Django 5.2.15 on 2026-07-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0011_anexo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Carrossel', max_length=200, verbose_name='Nome do carrossel')),
                ('ativo', models.BooleanField(default=False, help_text='Se marcado, o carrossel aparece na área dos cartazes da página inicial. Se desmarcado, não aparece.', verbose_name='Ativar carrossel')),
                ('lado', models.CharField(choices=[('esquerdo', 'Lado esquerdo'), ('direito', 'Lado direito')], default='direito', max_length=10, verbose_name='Lado da página')),
                ('largura', models.PositiveIntegerField(default=200, help_text='Largura do painel do carrossel em pixels. Ex.: 200', verbose_name='Largura (px)')),
                ('altura', models.PositiveIntegerField(default=356, help_text='Altura do painel do carrossel em pixels. Ex.: 356', verbose_name='Altura (px)')),
                ('intervalo', models.PositiveIntegerField(default=5, help_text='As imagens passam sozinhas a cada X segundos.', verbose_name='Tempo entre imagens (segundos)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem entre os cartazes')),
                ('codigo_html', models.TextField(blank=True, help_text='Avançado: cole aqui um código HTML completo para trocar a aparência do carrossel. Onde as imagens devem entrar, escreva o marcador <!--IMAGENS--> (ele é substituído pelas imagens cadastradas abaixo). Deixe em branco para usar o visual padrão.', verbose_name='Código HTML personalizado (opcional)')),
            ],
            options={
                'verbose_name': 'Carrossel',
                'verbose_name_plural': 'Carrosséis',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='url_imagem',
            field=models.URLField(blank=True, help_text='Cole aqui o endereço de uma imagem da internet para usá-la no lugar do arquivo enviado. Se os dois estiverem preenchidos, a URL tem prioridade.', verbose_name='Imagem por URL (opcional)'),
        ),
        migrations.AddField(
            model_name='cartaz',
            name='url_imagem',
            field=models.URLField(blank=True, help_text='Cole aqui o endereço de uma imagem da internet para usá-la como cartaz, no lugar do arquivo enviado. Se os dois estiverem preenchidos, a URL tem prioridade.', verbose_name='Imagem por URL (opcional)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='mostrar_menu_superior',
            field=models.BooleanField(default=True, help_text='Se marcado, o botão aparece na barra azul do topo da página inicial e na lista "Navegação" do rodapé. Se desmarcado, some dessas duas barras (mas a página da categoria continua existindo). Vale apenas para botões do nível principal.', verbose_name='Aparecer na barra superior do site'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='mostrar_navegue_area',
            field=models.BooleanField(default=True, help_text='Se marcado, o botão aparece na seção "Navegue por área" da página inicial. Se desmarcado, não aparece lá. Vale apenas para botões do nível principal.', verbose_name='Aparecer no "Navegue por área"'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagem do banner'),
        ),
        migrations.AlterField(
            model_name='cartaz',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cartazes/', verbose_name='Imagem do cartaz'),
        ),
        migrations.CreateModel(
            name='CarrosselImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='carrossel/', verbose_name='Imagem (arquivo)')),
                ('url_imagem', models.URLField(blank=True, help_text='Cole o endereço de uma imagem da internet. Se os dois estiverem preenchidos, a URL tem prioridade.', verbose_name='Imagem por URL')),
                ('link', models.URLField(blank=True, verbose_name='Link ao clicar (opcional)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('carrossel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='conteudo.carrossel', verbose_name='Carrossel')),
            ],
            options={
                'verbose_name': 'Imagem do carrossel',
                'verbose_name_plural': 'Imagens do carrossel',
                'ordering': ['ordem', 'pk'],
            },
        ),
    ]
