# Generated by Django 5.2.15 on 2026-07-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0012_carrossel_banner_url_imagem_cartaz_url_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='icone_imagem',
            field=models.FileField(blank=True, help_text='Envie uma imagem para usar como ícone do card, no lugar do ícone automático. Aceita qualquer formato (PNG, JPG, SVG, ICO, WEBP...). Use uma imagem com fundo transparente para não prejudicar a estética do botão. Se preenchido, tem prioridade sobre o ícone escolhido.', null=True, upload_to='icones/', verbose_name='Ícone personalizado (imagem)'),
        ),
    ]
