# Generated by Django 5.2.15 on 2026-07-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0013_conteudo_icone_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone_imagem',
            field=models.FileField(blank=True, help_text='Envie uma imagem para usar como ícone deste botão, no lugar do ícone automático/Font Awesome. Aceita qualquer formato (PNG, JPG, SVG, ICO, WEBP...). Use uma imagem com fundo transparente para não prejudicar a estética do botão. A imagem é ajustada automaticamente ao espaço do ícone (sem cortar) tanto no botão principal quanto em subbotões. Se preenchido, tem prioridade sobre o ícone escolhido.', null=True, upload_to='icones_categoria/', verbose_name='Ícone personalizado (imagem)'),
        ),
    ]
