# Generated by Django 5.2.15 on 2026-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0014_categoria_icone_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosselimagem',
            name='imagem',
            field=models.FileField(blank=True, help_text='Aceita imagem (JPG, PNG, GIF, WEBP...) ou vídeo (MP4, WEBM...).', null=True, upload_to='carrossel/', verbose_name='Imagem ou vídeo (arquivo)'),
        ),
        migrations.AlterField(
            model_name='carrosselimagem',
            name='url_imagem',
            field=models.URLField(blank=True, help_text='Cole o endereço de uma imagem ou vídeo da internet. Se os dois estiverem preenchidos, a URL tem prioridade.', verbose_name='Imagem/vídeo por URL'),
        ),
    ]
