# Generated by Django 5.2.15 on 2026-07-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0015_alter_carrosselimagem_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='texto_alinhamento',
            field=models.CharField(blank=True, choices=[('', 'Automático (padrão do site)'), ('left', 'Esquerda'), ('center', 'Centralizado'), ('right', 'Direita')], help_text='Alinhamento do título do card no site.', max_length=10, verbose_name='Alinhamento do texto'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='texto_fonte',
            field=models.CharField(blank=True, help_text='Ex.: Georgia, Arial, Times New Roman. Vazio = fonte do site (Inter).', max_length=100, verbose_name='Fonte do texto'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='texto_tamanho_fonte',
            field=models.PositiveIntegerField(blank=True, help_text='Vazio = tamanho automático do card.', null=True, verbose_name='Tamanho da letra (px)'),
        ),
    ]
