# Generated by Django 5.2.15 on 2026-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0016_conteudo_texto_alinhamento_conteudo_texto_fonte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, help_text='Opcional. Deixe em branco se não quiser nenhum texto sobre o banner.', max_length=200, verbose_name='Título'),
        ),
    ]
