# Generated by Django 5.2.15 on 2026-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0017_alter_banner_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='titulo',
            field=models.CharField(blank=True, help_text='Opcional. Deixe em branco para postar só uma imagem/vídeo, sem nenhum texto aparecendo sobre ela.', max_length=300, verbose_name='Título'),
        ),
    ]
