# Generated by Django 5.2.15 on 2026-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0018_alter_conteudo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Respondido em'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='resposta',
            field=models.TextField(blank=True, help_text='Resposta que aparece vinculada ao comentário no site. Deixe vazio se não quiser responder.', verbose_name='Resposta do administrador'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='status',
            field=models.CharField(choices=[('pendente', '⏳ Pendente'), ('publicado', '✅ Publicado'), ('recusado', '❌ Recusado')], default='pendente', help_text='Pendente = aguardando moderação; Publicado = visível no site; Recusado = descartado.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='aprovado',
            field=models.BooleanField(default=False, editable=False, verbose_name='Aprovado (legado)'),
        ),
    ]
