# Generated by Django 5.2.15 on 2026-07-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0020_comentario_parent_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_col1_html',
            field=models.TextField(blank=True, verbose_name='Rodape: conteudo coluna 1 (HTML)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_col1_titulo',
            field=models.CharField(blank=True, default='GERENCIA DE CURRICULO DA EDUCACAO BASICA (GECEB)', max_length=200, verbose_name='Rodape: titulo coluna 1'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_col2_html',
            field=models.TextField(blank=True, verbose_name='Rodape: conteudo coluna 2 (HTML)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_col2_titulo',
            field=models.CharField(blank=True, default='SECRETARIA DA EDUCACAO (SEDU)', max_length=200, verbose_name='Rodape: titulo coluna 2'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_col3_html',
            field=models.TextField(blank=True, help_text='Se vazio, exibe links automaticos das categorias do menu.', verbose_name='Rodape: conteudo coluna 3 (HTML)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_col3_titulo',
            field=models.CharField(blank=True, default='Navegacao', max_length=200, verbose_name='Rodape: titulo coluna 3'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_copyright',
            field=models.CharField(blank=True, max_length=300, verbose_name='Rodape: texto copyright'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Rodape: imagem/logo'),
        ),
    ]
