# Generated by Django 5.2.15 on 2026-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0021_rodape_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='mostrar_menu_superior',
            field=models.BooleanField(default=False, help_text='Se marcado, o botão aparece na barra azul do topo da página inicial e na lista "Navegação" do rodapé. Se desmarcado, some dessas duas barras (mas a página da categoria continua existindo). Vale apenas para botões do nível principal.', verbose_name='Aparecer na barra superior do site'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='mostrar_navegue_area',
            field=models.BooleanField(default=False, help_text='Se marcado, o botão aparece na seção "Navegue por área" da página inicial. Se desmarcado, não aparece lá. Vale apenas para botões do nível principal.', verbose_name='Aparecer no "Navegue por área"'),
        ),
    ]
