# Generated by Django 5.2.15 on 2026-07-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0022_default_false_visibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mostrar_conteudos_recentes',
            field=models.BooleanField(default=False, help_text='Se marcado, os conteúdos desta categoria poderão aparecer automaticamente na área "Conteúdos Recentes" da página inicial.', verbose_name='Aparecer em Conteúdos Recentes'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Opcional. Se preenchido, ao clicar neste botão o visitante será direcionado para este endereço externo em vez de abrir a página interna da categoria.', max_length=500, verbose_name='URL / Link de acesso externo'),
        ),
    ]
