# Generated by Django 5.2.15 on 2026-07-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0023_url_externa_e_recentes_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mostrar_area_central',
            field=models.BooleanField(default=False, help_text='Se marcado, o botão aparece centralizado na página inicial, ao lado do botão "Currículo Atual". Independente da barra superior — pode marcar um, outro, os dois ou nenhum. A ordem de exibição usa o mesmo campo "Ordem no menu". Vale apenas para botões do nível principal.', verbose_name='Aparecer na área central (ao lado do Currículo Atual)'),
        ),
    ]
