# Generated by Django 5.2.15 on 2026-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0024_mostrar_area_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mostrar_como_card',
            field=models.BooleanField(default=True, help_text='Vale apenas para subcategorias (botões dentro de outro botão). Se marcado, aparece como chip no topo E como card grande clicável no meio da página do pai. Se desmarcado, aparece SOMENTE como chip no topo (sem duplicar). Subáreas criadas pela função "Criar subárea nos botões marcados" já nascem desmarcadas, por padrão.', verbose_name='Mostrar como card grande na página do pai'),
        ),
    ]
