# Generated by Django 5.2.15 on 2026-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0025_mostrar_como_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='destaque_gerenciado',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente para itens criados na área "Destaques do Site" do Organizador de Conteúdo. Mantém o item visível na lista de gerenciamento mesmo quando ocultado (destaque=False), para poder reativar depois.', verbose_name='Cadastrado pela área "Destaques do Site" (Organizador)'),
        ),
    ]
