# Generated by Django 5.2.15 on 2026-07-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0026_destaque_gerenciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título da coluna')),
                ('lado', models.CharField(choices=[('esquerda', 'Esquerda'), ('direita', 'Direita')], default='direita', max_length=10, verbose_name='Lado')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa (aparece no site)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Coluna extra da home',
                'verbose_name_plural': 'Colunas extras da home',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo_areas',
            field=models.TextField(blank=True, default='Navegue por área', verbose_name='Título da seção "Navegue por área"'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo_destaques',
            field=models.TextField(blank=True, default='Destaques', verbose_name='Título da seção "Destaques"'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo_recentes',
            field=models.TextField(blank=True, default='Conteúdos recentes', verbose_name='Título da seção "Conteúdos recentes"'),
        ),
        migrations.CreateModel(
            name='ColunaExtraBotao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do botão')),
                ('link_externo', models.URLField(blank=True, help_text='Se preenchido, tem prioridade sobre a categoria escolhida.', verbose_name='Link externo (opcional)')),
                ('icone', models.CharField(blank=True, default='fas fa-link', max_length=100, verbose_name='Ícone Font Awesome')),
                ('icone_imagem', models.FileField(blank=True, null=True, upload_to='icones_coluna_extra/', verbose_name='Ícone personalizado (imagem)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('categoria', models.ForeignKey(blank=True, help_text='Se escolhida, o botão abre esta categoria do site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conteudo.categoria', verbose_name='Categoria (opcional)')),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botoes', to='conteudo.colunaextra', verbose_name='Coluna')),
            ],
            options={
                'verbose_name': 'Botão da coluna extra',
                'verbose_name_plural': 'Botões da coluna extra',
                'ordering': ['ordem', 'pk'],
            },
        ),
    ]
