# Generated by Django 5.2.15 on 2026-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0027_colunaextra_configuracaosite_titulo_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_areas',
            field=models.CharField(blank=True, default='fas fa-compass', max_length=100, verbose_name='Ícone de "Navegue por área" (padrão do site)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_areas_imagem',
            field=models.FileField(blank=True, null=True, upload_to='icones_secao/', verbose_name='Ícone de "Navegue por área" (imagem)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_destaques',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ícone de "Destaques" (padrão do site)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_destaques_imagem',
            field=models.FileField(blank=True, null=True, upload_to='icones_secao/', verbose_name='Ícone de "Destaques" (imagem)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_recentes',
            field=models.CharField(blank=True, default='fas fa-wand-magic-sparkles', max_length=100, verbose_name='Ícone de "Conteúdos recentes" (padrão do site)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_recentes_imagem',
            field=models.FileField(blank=True, null=True, upload_to='icones_secao/', verbose_name='Ícone de "Conteúdos recentes" (imagem)'),
        ),
    ]
