# Generated by Django 5.2.15 on 2026-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0028_configuracaosite_icone_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colunaextra',
            name='icone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ícone do título (padrão do site)'),
        ),
        migrations.AddField(
            model_name='colunaextra',
            name='icone_imagem',
            field=models.FileField(blank=True, help_text='Qualquer formato. Tem prioridade sobre o ícone padrão e aparece sempre com fundo transparente.', null=True, upload_to='icones_secao/', verbose_name='Ícone do título (imagem)'),
        ),
    ]
