# Generated by Django 5.2.15 on 2026-07-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0030_alter_configuracaosite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='altura_personalizada',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Deixe vazio para usar Pequeno/Médio/Grande acima. Se preenchido, define a altura exata do banner em pixels (vale em qualquer tamanho de tela — não diminui sozinho no celular).', null=True, verbose_name='Altura personalizada (px)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tamanho',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio (padrão)'), ('grande', 'Grande')], default='medio', help_text='Controla a altura máxima do banner. A imagem nunca é cortada ou distorcida. Ignorado se "Altura personalizada" (abaixo) estiver preenchida.', max_length=10, verbose_name='Tamanho da imagem'),
        ),
    ]
