# Generated by Django 5.2.15 on 2026-07-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0031_banner_altura_personalizada_alter_banner_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='altura_personalizada',
            field=models.PositiveIntegerField(blank=True, help_text='DEIXE VAZIO (recomendado): o banner se ajusta sozinho a qualquer imagem — ocupa a largura toda da página e a altura acompanha a proporção da imagem, sem cortar nenhuma parte e sem barras nas laterais. Só preencha se quiser FORÇAR uma altura fixa em pixels (nesse caso a imagem aparece inteira dentro da faixa, com um fundo desfocado preenchendo as sobras).', null=True, verbose_name='Altura fixa em pixels (opcional)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tamanho',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio (padrão)'), ('grande', 'Grande')], default='medio', help_text='Campo legado — hoje o banner se ajusta AUTOMATICAMENTE à imagem (ocupa a largura toda e a altura acompanha a proporção, sem cortar). Só tem efeito se você NÃO usar o ajuste automático via "Altura personalizada".', max_length=10, verbose_name='Tamanho da imagem'),
        ),
    ]
