# Generated by Django 5.2.15 on 2026-07-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0032_alter_banner_altura_personalizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='altura_personalizada',
            field=models.PositiveIntegerField(blank=True, help_text='VAZIO: o banner se ajusta sozinho à imagem (ocupa a largura toda e a altura acompanha a proporção, sem cortar). PREENCHA um número para deixar o banner com uma altura fixa — ótimo para uma FAIXA FINA E DISCRETA (ex.: 120, 150). Nesse caso a imagem PREENCHE a faixa (pode recortar um pouco o topo/base para caber), sem barras nem desfoque. Quanto menor o número, mais fina a faixa.', null=True, verbose_name='Altura fixa em pixels (opcional)'),
        ),
    ]
