# Generated by Django 5.2.15 on 2026-07-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0033_alter_banner_altura_personalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodapeImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(help_text='Qualquer formato de imagem (PNG, JPG, SVG, WEBP...).', upload_to='rodape_imagens/', verbose_name='Imagem')),
                ('largura', models.PositiveIntegerField(blank=True, help_text='Vazio = largura automática, proporcional à altura.', null=True, verbose_name='Largura (px)')),
                ('altura', models.PositiveIntegerField(blank=True, help_text='Vazio = altura automática. A imagem nunca aumenta a altura do rodapé — ela sempre se ajusta ao espaço fixo já reservado.', null=True, verbose_name='Altura (px)')),
                ('alinhamento', models.CharField(choices=[('esquerda', 'Esquerda'), ('centro', 'Centralizado'), ('direita', 'Direita')], default='esquerda', max_length=10, verbose_name='Alinhamento')),
                ('url', models.URLField(blank=True, help_text='Se preenchida, a imagem funciona como link. Se vazia, é exibida sem link.', verbose_name='URL (opcional)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Imagem do rodapé',
                'verbose_name_plural': 'Imagens do rodapé',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='brasao_alinhamento',
            field=models.CharField(choices=[('esquerda', 'Esquerda'), ('centro', 'Centro'), ('direita', 'Direita')], default='esquerda', max_length=10, verbose_name='Alinhamento do brasão'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='brasao_altura',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura do brasão (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='brasao_imagem',
            field=models.FileField(blank=True, help_text='Se vazio, usa o brasão padrão do Espírito Santo. Envie uma imagem para substituí-lo (fundo transparente recomendado).', null=True, upload_to='identidade/', verbose_name='Brasão personalizado (opcional)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='brasao_largura',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura do brasão (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='logo2_alinhamento',
            field=models.CharField(choices=[('esquerda', 'Esquerda'), ('centro', 'Centro'), ('direita', 'Direita')], default='esquerda', max_length=10, verbose_name='Alinhamento do segundo logotipo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='logo2_altura',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura do segundo logotipo (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='logo2_imagem',
            field=models.FileField(blank=True, help_text='Ex.: logo do Currículo. Aparece na barra superior ao lado do brasão. Deixe vazio para não exibir nenhum segundo logotipo.', null=True, upload_to='identidade/', verbose_name='Segundo logotipo (opcional)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='logo2_largura',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura do segundo logotipo (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='nome_curriculo_atual',
            field=models.CharField(blank=True, default='Currículo Atual', help_text='Texto exibido na pílula central da página inicial. Deixe vazio para usar "Currículo Atual" (padrão).', max_length=100, verbose_name='Nome do botão "Currículo Atual"'),
        ),
    ]
