# Generated by Django 5.2.15 on 2026-07-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0034_rodapeimagem_configuracaosite_brasao_alinhamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando o comentário foi feito na página de um botão (categoria) em vez de num conteúdo específico. Mutuamente exclusivo com Conteúdo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='conteudo.categoria', verbose_name='Botão/categoria'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='conteudo.conteudo', verbose_name='Conteúdo'),
        ),
    ]
