# Generated by Django 5.2.15 on 2026-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0035_comentario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colunaextra',
            name='titulo',
            field=models.TextField(blank=True, help_text='Aceita formatação (negrito, itálico, alinhamento, lista) — mesmo editor usado em Destaques/Recentes/Navegue por área.', verbose_name='Título da coluna'),
        ),
    ]
