# Generated by Django 5.2.15 on 2026-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0036_coluna_extra_titulo_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='url',
            field=models.URLField(blank=True, help_text='Em vez de um arquivo, aponta para um link externo. Aparece no site exatamente como um anexo de arquivo, só que abre a URL. Preencha OU o arquivo OU o link — nunca os dois.', max_length=500, verbose_name='Link (URL)'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(blank=True, help_text='PDF, Word, Excel, PowerPoint, vídeo, imagem ou outro arquivo.', upload_to='anexos/%Y/%m/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome exibido no site. Se vazio, usa o nome do arquivo (ou o link, se for um anexo de URL).', max_length=200, verbose_name='Nome de exibição'),
        ),
    ]
