# Generated by Django 5.2.15 on 2026-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0037_anexo_url_alter_anexo_arquivo_alter_anexo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='url',
            field=models.URLField(blank=True, help_text='Em vez de um arquivo, aponta para um link externo. Aparece no site exatamente como um anexo de arquivo, só que abre a URL. Preencha OU o arquivo OU o link — nunca os dois.', max_length=1000, verbose_name='Link (URL)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Link ao clicar'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url_imagem',
            field=models.URLField(blank=True, help_text='Cole aqui o endereço de uma imagem da internet para usá-la no lugar do arquivo enviado. Se os dois estiverem preenchidos, a URL tem prioridade.', max_length=1000, verbose_name='Imagem por URL (opcional)'),
        ),
        migrations.AlterField(
            model_name='carrosselimagem',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Link ao clicar (opcional)'),
        ),
        migrations.AlterField(
            model_name='carrosselimagem',
            name='url_imagem',
            field=models.URLField(blank=True, help_text='Cole o endereço de uma imagem ou vídeo da internet. Se os dois estiverem preenchidos, a URL tem prioridade.', max_length=1000, verbose_name='Imagem/vídeo por URL'),
        ),
        migrations.AlterField(
            model_name='cartaz',
            name='link',
            field=models.URLField(blank=True, help_text='URL para inscrição ou página do evento', max_length=1000, verbose_name='Link do evento'),
        ),
        migrations.AlterField(
            model_name='cartaz',
            name='url_imagem',
            field=models.URLField(blank=True, help_text='Cole aqui o endereço de uma imagem da internet para usá-la como cartaz, no lugar do arquivo enviado. Se os dois estiverem preenchidos, a URL tem prioridade.', max_length=1000, verbose_name='Imagem por URL (opcional)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Opcional. Se preenchido, ao clicar neste botão o visitante será direcionado para este endereço externo em vez de abrir a página interna da categoria.', max_length=1000, verbose_name='URL / Link de acesso externo'),
        ),
        migrations.AlterField(
            model_name='colunaextrabotao',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Se preenchido, tem prioridade sobre a categoria escolhida.', max_length=1000, verbose_name='Link externo (opcional)'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='url_externa',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Link externo'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='url_video',
            field=models.URLField(blank=True, help_text='Cole o link do YouTube ou Vimeo', max_length=1000, verbose_name='URL do vídeo'),
        ),
        migrations.AlterField(
            model_name='rodapeimagem',
            name='url',
            field=models.URLField(blank=True, help_text='Se preenchida, a imagem funciona como link. Se vazia, é exibida sem link.', max_length=1000, verbose_name='URL (opcional)'),
        ),
    ]
