# Generated by Django 5.2.15 on 2026-07-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0038_url_fields_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone_altura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se vazio e a largura estiver preenchida, usa o mesmo valor da largura (ícone quadrado).', null=True, verbose_name='Altura do ícone (px)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone_largura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Controla o tamanho do ícone deste botão em pixels (Font Awesome ou imagem personalizada). Deixe em branco para usar o tamanho padrão do site.', null=True, verbose_name='Largura do ícone (px)'),
        ),
    ]
