# Generated by Django 5.2.15 on 2026-07-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0039_categoria_icone_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='colunaextrabotao',
            name='icone_altura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se vazio e a largura estiver preenchida, usa o mesmo valor (ícone quadrado).', null=True, verbose_name='Altura do ícone (px)'),
        ),
        migrations.AddField(
            model_name='colunaextrabotao',
            name='icone_largura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Deixe em branco para usar o tamanho padrão.', null=True, verbose_name='Largura do ícone (px)'),
        ),
    ]
