# Generated by Django 5.2.15 on 2026-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0041_colunaextra_icone_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='teams_data_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado ao Teams em'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='teams_message_id',
            field=models.CharField(blank=True, help_text='ID da mensagem raiz criada no canal do Teams para este comentário (uso interno).', max_length=255, verbose_name='ID da mensagem no Teams'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='teams_status',
            field=models.CharField(blank=True, choices=[('nao_enviado', '— Não enviado'), ('enviado', '📤 Enviado ao Teams'), ('vinculado', '🔗 Vinculado (aguardando resposta)'), ('respondido', '✅ Respondido via Teams'), ('erro', '⚠️ Erro ao enviar')], default='nao_enviado', help_text='Controlado automaticamente pela integração com o Microsoft Teams (grupo GECEB).', max_length=12, verbose_name='Status no Teams'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='teams_ultima_verificacao',
            field=models.DateTimeField(blank=True, help_text='Usado pela sincronização automática para não reprocessar tudo a cada rodada.', null=True, verbose_name='Última verificação de resposta'),
        ),
    ]
