# Generated by Django 5.2.15 on 2026-07-23 18:39

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0042_comentario_teams_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'base_manager_name': 'todos_objetos', 'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='conteudo',
            options={'base_manager_name': 'todos_objetos', 'ordering': ['-destaque', 'ordem', '-data_publicacao'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterModelManagers(
            name='categoria',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos_objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='conteudo',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos_objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Preenchido automaticamente quando o botão vai para a lixeira. Fica recuperável por 30 dias — ver painel "Lixeira".', null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Preenchido automaticamente quando o conteúdo vai para a lixeira. Fica recuperável por 30 dias — ver painel "Lixeira".', null=True, verbose_name='Excluído em'),
        ),
    ]
