# Generated by Django 5.2.15 on 2026-07-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0043_lixeira_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosite',
            options={'permissions': [('pode_acessar_organizador', 'Pode acessar: Organizador de Conteúdo'), ('pode_acessar_adicionar_arquivos', 'Pode acessar: Adicionar Arquivos'), ('pode_acessar_barra_superior', 'Pode acessar: Botões da Barra Superior'), ('pode_acessar_editor_rodape', 'Pode acessar: Editor do Rodapé'), ('pode_acessar_area_do_site', 'Pode acessar: Área do Site'), ('pode_acessar_estrutura_arvores', 'Pode acessar: Estrutura de Árvores'), ('pode_acessar_lixeira', 'Pode acessar: Lixeira')], 'verbose_name': 'Configuração do site', 'verbose_name_plural': 'Configuração do site'},
        ),
    ]
