# Generated by Django 5.2.15 on 2026-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0044_lixeira_permissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_areas_altura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se vazio e a largura estiver preenchida, usa o mesmo valor (ícone quadrado).', null=True, verbose_name='Altura do ícone de "Navegue por área" (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_areas_largura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Deixe em branco para usar o tamanho padrão.', null=True, verbose_name='Largura do ícone de "Navegue por área" (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_destaques_altura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se vazio e a largura estiver preenchida, usa o mesmo valor (ícone quadrado).', null=True, verbose_name='Altura do ícone de "Destaques" (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_destaques_largura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Deixe em branco para usar o tamanho padrão.', null=True, verbose_name='Largura do ícone de "Destaques" (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_recentes_altura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se vazio e a largura estiver preenchida, usa o mesmo valor (ícone quadrado).', null=True, verbose_name='Altura do ícone de "Conteúdos recentes" (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='icone_recentes_largura',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Deixe em branco para usar o tamanho padrão.', null=True, verbose_name='Largura do ícone de "Conteúdos recentes" (px)'),
        ),
    ]
