# Generated by Django 5.2.15 on 2026-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0045_configuracaosite_icone_areas_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='home_intro_altura',
            field=models.PositiveIntegerField(blank=True, help_text='Vazio = altura automática, conforme o título/texto.', null=True, verbose_name='Altura mínima da barra (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='home_intro_cor_fundo',
            field=models.CharField(blank=True, help_text='Vazio = azul padrão do site (#1e3a5f).', max_length=20, verbose_name='Cor de fundo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='home_intro_imagem',
            field=models.FileField(blank=True, help_text='Aparece como imagem de fundo, atrás do título/texto, com uma camada semi-transparente por cima (na cor de fundo escolhida, ou azul padrão) para manter o texto sempre legível. Aceita qualquer formato de imagem.', null=True, upload_to='home_intro/', verbose_name='Imagem de fundo (opcional)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='home_intro_largura',
            field=models.PositiveIntegerField(blank=True, help_text='Controla até onde o título/texto podem esticar antes de quebrar linha, dentro da barra (que continua ocupando a largura toda da tela). Vazio = usa o espaço disponível todo, sem quebrar cedo.', null=True, verbose_name='Largura máxima do conteúdo (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='home_intro_texto_tamanho_fonte',
            field=models.PositiveIntegerField(blank=True, help_text='Vazio = tamanho automático do site.', null=True, verbose_name='Tamanho da letra do texto (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='home_intro_titulo_tamanho_fonte',
            field=models.PositiveIntegerField(blank=True, help_text='Vazio = tamanho automático do site.', null=True, verbose_name='Tamanho da letra do título (px)'),
        ),
    ]
