# Generated by Django 5.2.15 on 2026-07-24 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0046_configuracaosite_home_intro_altura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL amigável')),
                ('conteudo', models.TextField(blank=True, help_text='Texto livre exibido no topo da página — aceita formatação (negrito, itálico, sublinhado, alinhamento, lista).', verbose_name='Texto da página')),
                ('ativa', models.BooleanField(default=True, help_text='Se desmarcada, a página deixa de existir no site (404), mesmo que alguém tenha o link.', verbose_name='Ativa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Página livre',
                'verbose_name_plural': 'Páginas livres',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='configuracaosite',
            options={'permissions': [('pode_acessar_organizador', 'Pode acessar: Organizador de Conteúdo'), ('pode_acessar_adicionar_arquivos', 'Pode acessar: Adicionar Arquivos'), ('pode_acessar_barra_superior', 'Pode acessar: Botões da Barra Superior'), ('pode_acessar_editor_rodape', 'Pode acessar: Editor do Rodapé'), ('pode_acessar_area_do_site', 'Pode acessar: Área do Site'), ('pode_acessar_estrutura_arvores', 'Pode acessar: Estrutura de Árvores'), ('pode_acessar_lixeira', 'Pode acessar: Lixeira'), ('pode_acessar_paginas_livres', 'Pode acessar: Páginas Livres')], 'verbose_name': 'Configuração do site', 'verbose_name_plural': 'Configuração do site'},
        ),
        migrations.AddField(
            model_name='comentario',
            name='pagina_livre',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando o comentário foi feito numa Página Livre. Mutuamente exclusivo com Conteúdo/Categoria.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='conteudo.paginalivre', verbose_name='Página livre'),
        ),
        migrations.CreateModel(
            name='PaginaLivreBotao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do botão')),
                ('link_externo', models.URLField(blank=True, help_text='Se preenchido, tem prioridade sobre a categoria escolhida.', max_length=1000, verbose_name='Link externo (opcional)')),
                ('icone', models.CharField(blank=True, default='fas fa-link', max_length=100, verbose_name='Ícone Font Awesome')),
                ('icone_imagem', models.FileField(blank=True, null=True, upload_to='icones_pagina_livre/', verbose_name='Ícone personalizado (imagem)')),
                ('icone_largura', models.PositiveIntegerField(blank=True, help_text='Opcional. Deixe em branco para usar o tamanho padrão.', null=True, verbose_name='Largura do ícone (px)')),
                ('icone_altura', models.PositiveIntegerField(blank=True, help_text='Opcional. Se vazio e a largura estiver preenchida, usa o mesmo valor (ícone quadrado).', null=True, verbose_name='Altura do ícone (px)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('categoria', models.ForeignKey(blank=True, help_text='Se escolhida, o botão abre esta categoria do site (sem tirá-la do lugar onde já está).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conteudo.categoria', verbose_name='Categoria (opcional)')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botoes', to='conteudo.paginalivre', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Botão da página livre',
                'verbose_name_plural': 'Botões da página livre',
                'ordering': ['ordem', 'pk'],
            },
        ),
    ]
