# Generated by Django 5.2.15 on 2026-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaInteligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sem_acesso', 'Documento sem acesso'), ('link_quebrado', 'Link quebrado'), ('arquivo_ausente', 'Arquivo ausente'), ('pico_acesso', 'Pico de acesso'), ('erro_pagina', 'Página com erro')], max_length=30)),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=20)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('conteudo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nome_arquivo', models.CharField(max_length=300)),
                ('extensao', models.CharField(blank=True, max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sessao_id', models.CharField(blank=True, max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=300)),
                ('termo_normalizado', models.CharField(db_index=True, max_length=300)),
                ('n_resultados', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sessao_id', models.CharField(blank=True, max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pesquisa interna',
                'verbose_name_plural': 'Pesquisas internas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('tipo_pagina', models.CharField(choices=[('home', 'Home'), ('categoria', 'Categoria'), ('conteudo', 'Conteúdo'), ('busca', 'Busca'), ('outra', 'Outra')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_slug', models.SlugField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sessao_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('dispositivo', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], default='desktop', max_length=10)),
                ('navegador', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Visualização de página',
                'verbose_name_plural': 'Visualizações de página',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tipo_pagina', 'timestamp'], name='inteligenci_tipo_pa_834e5f_idx'), models.Index(fields=['objeto_id', 'tipo_pagina'], name='inteligenci_objeto__e4f50e_idx')],
            },
        ),
    ]
