# Generated by Django 5.2.15 on 2026-07-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertainteligencia',
            options={'ordering': ['-criado_em'], 'permissions': [('pode_acessar_inteligencia', 'Pode acessar: Central de Inteligência')], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
    ]
