# Generated by Django 5.2.15 on 2026-07-04 16:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem do banner')),
                ('link', models.URLField(blank=True, verbose_name='Link ao clicar')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='Currículo do Espírito Santo', max_length=200, verbose_name='Nome do site')),
                ('descricao', models.TextField(default='Currículo da Educação Básica do Espírito Santo', verbose_name='Descrição')),
                ('email_contato', models.EmailField(default='gerenciadecurriculo@sedu.es.gov.br', max_length=254, verbose_name='E-mail de contato')),
                ('telefone', models.CharField(default='(27) 3636-7838 / 7842', max_length=50, verbose_name='Telefone')),
                ('endereco', models.TextField(default='Av. César Hilal, 1111 – Santa Lúcia\nCEP: 29056-085 – Vitória / ES', verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configuração do site',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL amigável')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone (ex: fas fa-book, fas fa-trophy)', max_length=50, verbose_name='Ícone')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagem de capa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem no menu')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='conteudo.categoria', verbose_name='Categoria pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL amigável')),
                ('tipo', models.CharField(choices=[('documento', 'Documento (PDF, Word, Excel)'), ('video', 'Vídeo'), ('post', 'Post / Texto'), ('link', 'Link externo'), ('pagina', 'Página completa')], default='post', max_length=20, verbose_name='Tipo de conteúdo')),
                ('resumo', models.TextField(blank=True, help_text='Breve descrição exibida nos cards', verbose_name='Resumo')),
                ('corpo', models.TextField(blank=True, help_text='Texto com formatação HTML', verbose_name='Conteúdo completo')),
                ('arquivo', models.FileField(blank=True, help_text='PDF, Word (.docx), Excel (.xlsx) ou outro arquivo', null=True, upload_to='documentos/%Y/%m/', verbose_name='Arquivo')),
                ('url_video', models.URLField(blank=True, help_text='Cole o link do YouTube ou Vimeo', verbose_name='URL do vídeo')),
                ('url_externa', models.URLField(blank=True, verbose_name='Link externo')),
                ('imagem_destaque', models.ImageField(blank=True, help_text='Imagem exibida no card e no topo da página', null=True, upload_to='destaques/%Y/%m/', verbose_name='Imagem de destaque')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para exibir este conteúdo na página principal', verbose_name='Destaque na home')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.CharField(blank=True, max_length=200, verbose_name='Autor / Responsável')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos', to='conteudo.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['-destaque', 'ordem', '-data_publicacao'],
            },
        ),
    ]
