# Generated by Django 5.2.15 on 2026-07-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Deixe vazio para aparecer na página inicial. Selecione uma área para o banner aparecer dentro daquela seção.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='conteudo.categoria', verbose_name='Área de exibição'),
        ),
    ]
