# Generated by Django 5.2.15 on 2026-07-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_banner_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tamanho',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio (padrão)'), ('grande', 'Grande')], default='medio', help_text='Controla a altura máxima do banner. A imagem nunca é cortada ou distorcida.', max_length=10, verbose_name='Tamanho da imagem'),
        ),
    ]
