# Generated by Django 5.2.15 on 2026-07-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0005_conteudo_icone_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do evento')),
                ('imagem', models.ImageField(upload_to='cartazes/', verbose_name='Imagem do cartaz')),
                ('link', models.URLField(blank=True, help_text='URL para inscrição ou página do evento', verbose_name='Link do evento')),
                ('lado', models.CharField(choices=[('esquerdo', 'Lado esquerdo'), ('direito', 'Lado direito')], default='esquerdo', max_length=10, verbose_name='Lado da página')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cartaz',
                'verbose_name_plural': 'Cartazes',
                'ordering': ['lado', 'ordem'],
            },
        ),
    ]
