# Generated by Django 5.2.15 on 2026-07-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0006_cartaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaz',
            name='tamanho',
            field=models.CharField(choices=[('pequeno', 'Pequeno (90px)'), ('medio', 'Médio (140px)'), ('grande', 'Grande (200px)')], default='pequeno', max_length=10, verbose_name='Tamanho do cartaz'),
        ),
    ]
