# Generated by Django 5.2.15 on 2026-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0007_cartaz_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='home_texto',
            field=models.TextField(blank=True, default='<p>Referencial curricular da Educação Básica, elaborado em regime de colaboração entre Estado e municípios.</p>', verbose_name='Texto da página inicial'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='home_titulo',
            field=models.CharField(default='Currículo do Espírito Santo', max_length=200, verbose_name='Título da página inicial'),
        ),
    ]
